### ISSUE TITLE
Does not conform to the spec when aborting an error

### ISSUE THREAD

**Issue by scinos** [wheresrhys/fetch-mock#416]
When a request is aborted, `fetch-mock` throws a regular `Error`, but the spec (and `node-fetch` behaviour) is to throw an `AbortError`.

Spec: https://dom.spec.whatwg.org/#aborting-ongoing-activities
> APIs that rely upon AbortController are encouraged to respond to abort() by rejecting any unsettled promise with a new "AbortError" DOMException.

Code in node-fetch throwing `AbortError` (correct): https://github.com/bitinn/node-fetch/blob/master/src/index.js#L53
```
const abort = ()  => {
	let error = new AbortError('The user aborted a request.');
	reject(error);
	if (request.body && request.body instanceof Stream.Readable) {
		request.body.destroy(error);
	}
	if (!response || !response.body) return;
	response.body.emit('error', error);
}
```

Similar code in `fetch-mock` throwing an `Error` (incorrect): https://github.com/wheresrhys/fetch-mock/blob/master/src/lib/fetch-handler.js#L42

```
if (options && options.signal) {
	const abort = () => {
		rej(new Error(`URL '${url}' aborted.`));
		done();
	};
	if (options.signal.aborted) {
		abort();
	}
	options.signal.addEventListener('abort', abort);
}
```

--- 
Example code:

```
// WORKING, outputs 'Aborted'
const fetch = require('node-fetch');

// NOT WORKING, outputs 'Other error'
// const fetch = require('fetch-mock').sandbox();
// fetch.mock('*', 200);

const AbortController = require('abort-controller');
const controller = new AbortController();
fetch('http://www.google.com', { signal: controller.signal }).catch(err => {
    if (err.name === 'AbortError') console.log('Aborted!');
    else console.log('Other error');
});
controller.abort();
```

**Comment by wheresrhys** [comment]
Would you like to submit a PR to fix this? Seems like you know what needs to be done. I don't have much free time at the moment and your help will be greatly appreciated

**Comment by scinos** [comment]
I'll try.

**Comment by wheresrhys** [comment]
Fixed in https://github.com/wheresrhys/fetch-mock/releases/tag/v7.3.8

Thanks for the PR @scinos

**Comment by Sayan751** [comment]
@wheresrhys It still does not conform to the spec. The thrown object needs to be an instance of [DOMException](https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException), with the `name` property set to `AbortError`, instead of an `Error`.

**Comment by Sayan751** [comment]
@wheresrhys Please consider reopening this

**Comment by wheresrhys** [comment]
I'd welcome a PR to address this

**Comment by Sayan751** [comment]
@wheresrhys Here is the PR: https://github.com/wheresrhys/fetch-mock/pull/485
